### PR TITLE
Memoize useCallbacks properly

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by donavon** [comment]
:doh: Nice catch. Thanks.

**Comment by donavon** [comment]
published as 2.1.1. Thanks again.

https://www.npmjs.com/package/use-dark-mode

**Comment by donavon** [comment]
@Andarist I'd like to add you to the all-contributors list. do you mind?

**Comment by Andarist** [comment]
I don't mind.

**Comment by donavon** [comment]
@allcontributors[bot] please add @Andarist for code

**Pull request merged**
